name: Sync Dinal Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Dinal fork
        run: |
          git remote add dinal https://x-access-token:${{ secrets.DINAL_PAT }}@github.com/Dinal2005/fridge-refill.git
          git push dinal main:main --force