# Generated by Django 5.2.5 on 2026-08-14 17:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('store_code', models.CharField(max_length=30, unique=True)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('product_photo', models.ImageField(blank=True, upload_to='products/%Y/%m/')),
                ('pack_size', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('barcode',), name='unique_nonempty_barcode'), models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('sku',), name='unique_nonempty_sku')],
            },
        ),
        migrations.CreateModel(
            name='RefillSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('PICKING', 'Picking'), ('REFILLING', 'Refilling'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_sessions', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('fridge_number', models.CharField(max_length=30)),
                ('location_description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='fridges/%Y/%m/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fridges', to='core.store')),
            ],
            options={
                'ordering': ['display_order', 'fridge_number'],
            },
        ),
        migrations.CreateModel(
            name='UserStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='employees',
            field=models.ManyToManyField(related_name='stores', through='core.UserStore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FridgeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('shelf_number', models.CharField(blank=True, max_length=30)),
                ('normal_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_display_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.fridge')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fridge_assignments', to='core.product')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('fridge', 'product'), name='unique_fridge_product')],
            },
        ),
        migrations.CreateModel(
            name='RefillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_quantity', models.PositiveIntegerField(default=0)),
                ('picked_quantity', models.PositiveIntegerField(default=0)),
                ('refilled_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('NEEDED', 'Needed'), ('PICKED', 'Picked'), ('SHORT', 'Short'), ('REFILLED', 'Refilled')], default='NEEDED', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fridge')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('refill_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.refillsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('refill_session', 'fridge', 'product'), name='unique_session_fridge_product')],
            },
        ),
        migrations.CreateModel(
            name='FridgeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('refilled', models.BooleanField(default=False)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fridge')),
                ('refill_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_checks', to='core.refillsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('refill_session', 'fridge'), name='unique_session_fridge_check')],
            },
        ),
        migrations.CreateModel(
            name='StockShortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_quantity', models.PositiveIntegerField()),
                ('found_quantity', models.PositiveIntegerField()),
                ('short_quantity', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('refill_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortages', to='core.refillsession')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('refill_session', 'product'), name='unique_session_product_shortage')],
            },
        ),
        migrations.AddConstraint(
            model_name='fridge',
            constraint=models.UniqueConstraint(fields=('store', 'fridge_number'), name='unique_store_fridge_number'),
        ),
        migrations.AddConstraint(
            model_name='userstore',
            constraint=models.UniqueConstraint(fields=('user', 'store'), name='unique_user_store'),
        ),
    ]
