# Generated by Django 5.2.5 on 2026-08-15 23:29

from django.db import migrations, models

def prepare_existing_assignments(apps, schema_editor):
    assignment = apps.get_model('core', 'FridgeProduct')
    assignment.objects.filter(shelf_number='').update(shelf_number='1')

def copy_display_order_to_position(apps, schema_editor):
    assignment = apps.get_model('core', 'FridgeProduct')
    for row in assignment.objects.all().iterator():
        row.position = row.display_order
        row.save(update_fields=['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fridgeproduct',
            options={'ordering': ['shelf_number', 'position', 'display_order', 'id']},
        ),
        migrations.AddField(
            model_name='fridgeproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fridgeproduct',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fridgeproduct',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fridgeproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='needs_verification',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='package_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(prepare_existing_assignments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fridgeproduct',
            name='shelf_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(copy_display_order_to_position, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='fridgeproduct',
            index=models.Index(fields=['fridge', 'shelf_number', 'position'], name='core_fridge_fridge__4e37c0_idx'),
        ),
    ]
